version: "3.7"

services:

  postgres:
    container_name: 'art-gallery-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=art-gallery'
      - 'POSTGRES_PASSWORD=password'
