version: "3.7"

services:
  backend:
    container_name: project-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=postgresdb
    links:
      - postgresdb
    depends_on:
      - postgresdb
    networks:
      - net

  postgresdb:
    container_name: 'project-db'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=art-gallery'
      - 'POSTGRES_PASSWORD=password'
    networks:
      - net

volumes:
  db_data:

networks:
  net: {}
